name: daunused_example
description: Example code for the daunused library.
version: 1.0.0+1
homepage: https://github.com/mauriciotogneri/daunused

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter