name: daunused
description: A Dart package that checks for unused files in your project.
version: 1.9.0
homepage: https://github.com/mauriciotogneri/daunused

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  analyzer: ^13.0.0
